//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilan_pointvue_formateur
    {
        public int id_bilan_pointvue_formateur { get; set; }
        public Nullable<int> prerequis { get; set; }
        public Nullable<int> qualite_ecoute { get; set; }
        public Nullable<int> integration_notions { get; set; }
        public Nullable<int> stage_correspond_besoin { get; set; }
        public string observations { get; set; }
        public int id_bilan_formation { get; set; }
    
        public virtual bilan_formation bilan_formation { get; set; }
    }
}
