//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilan_formation
    {
        public int id_bilan { get; set; }
        public Nullable<int> formateur_maitrise_sujet { get; set; }
        public Nullable<int> formateur_qualites_pedagogiques { get; set; }
        public Nullable<int> formateur_comprehension_problemes { get; set; }
        public Nullable<int> environnement_accueil { get; set; }
        public Nullable<int> environnement_salle_formation { get; set; }
        public Nullable<int> environnement_materiel_informatique { get; set; }
        public Nullable<int> environnement_support_cours { get; set; }
        public Nullable<int> formation_info_contenu { get; set; }
        public Nullable<int> formation_contenu_adapte { get; set; }
        public Nullable<int> formation_frequence_exercices { get; set; }
        public Nullable<int> formation_adaptation_exercices_profession { get; set; }
        public Nullable<int> formation_niveau_groupe_homogene { get; set; }
        public Nullable<int> formation_stage_correspondant_besoin { get; set; }
        public Nullable<int> satisfaction_globale { get; set; }
        public string points_forts_du_stage { get; set; }
        public string points_faibles_du_stage { get; set; }
        public string observations_diverses { get; set; }
        public string besoin_formation_complementaire { get; set; }
        public Nullable<int> pointvueformateur_prerequis { get; set; }
        public Nullable<int> pointvueformateur_qualite_ecoute { get; set; }
        public Nullable<int> pointvueformateur_integration_notions { get; set; }
        public Nullable<int> pointvueformateur_stage_correspond_besoin { get; set; }
    
        public virtual formateur formateur { get; set; }
        public virtual session_formation session_formation { get; set; }
        public virtual stagiaire stagiaire { get; set; }
    }
}
