//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilan_formation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bilan_formation()
        {
            this.bilan_eval_environnement = new HashSet<bilan_eval_environnement>();
            this.bilan_eval_formateur = new HashSet<bilan_eval_formateur>();
            this.bilan_eval_formation = new HashSet<bilan_eval_formation>();
            this.bilan_pointvue_formateur = new HashSet<bilan_pointvue_formateur>();
        }
    
        public int id_bilan_formation { get; set; }
        public Nullable<int> satisfaction_globale { get; set; }
        public string points_forts_du_stage { get; set; }
        public string points_faibles_du_stage { get; set; }
        public string observations_diverses { get; set; }
        public string besoin_formation_complementaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilan_eval_environnement> bilan_eval_environnement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilan_eval_formateur> bilan_eval_formateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilan_eval_formation> bilan_eval_formation { get; set; }
        public virtual formateur formateur { get; set; }
        public virtual session_formation session_formation { get; set; }
        public virtual stagiaire stagiaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilan_pointvue_formateur> bilan_pointvue_formateur { get; set; }
    }
}
