//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipement
    {
        public int id_equipement { get; set; }
        public string numero_serie { get; set; }
        public string type { get; set; }
        public Nullable<int> id_salle { get; set; }
    
        public virtual salle salle { get; set; }
    }
}
