//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class formateur_session_formation
    {
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<int> duree { get; set; }
        public Nullable<decimal> tarif { get; set; }
        public Nullable<decimal> frais { get; set; }
        public int id_formateur { get; set; }
        public int id_session_formation { get; set; }
    
        public virtual formateur formateur { get; set; }
        public virtual session_formation session_formation { get; set; }
    }
}
