//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class formation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formation()
        {
            this.formation_cursus = new HashSet<formation_cursus>();
            this.session_formation = new HashSet<session_formation>();
        }
    
        public int id_formation { get; set; }
        public Nullable<int> duree { get; set; }
        public Nullable<decimal> tarif_intra { get; set; }
        public Nullable<decimal> tarif_inter { get; set; }
        public string intitule { get; set; }
        public string niveau { get; set; }
        public int id_theme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formation_cursus> formation_cursus { get; set; }
        public virtual theme theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session_formation> session_formation { get; set; }
    }
}
