//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class formateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formateur()
        {
            this.bilan_formation = new HashSet<bilan_formation>();
            this.formateur_session_formation = new HashSet<formateur_session_formation>();
            this.theme_formateur = new HashSet<theme_formateur>();
        }
    
        public int id_formateur { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string statut { get; set; }
        public string telephone { get; set; }
        public string adresse { get; set; }
        public Nullable<decimal> cout { get; set; }
        public string civilite { get; set; }
        public string mail { get; set; }
        public Nullable<int> id_societe { get; set; }
        public Nullable<int> id_ville { get; set; }
        public Nullable<int> id_identificateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bilan_formation> bilan_formation { get; set; }
        public virtual identificateur identificateur { get; set; }
        public virtual societe societe { get; set; }
        public virtual ville ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formateur_session_formation> formateur_session_formation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<theme_formateur> theme_formateur { get; set; }
    }
}
