//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gest_formationEntities1 : DbContext
    {
        public gest_formationEntities1()
            : base("name=gest_formationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bilan_formation> bilan_formation { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<cursus> cursus { get; set; }
        public virtual DbSet<equipement> equipement { get; set; }
        public virtual DbSet<formateur> formateur { get; set; }
        public virtual DbSet<formateur_session_formation> formateur_session_formation { get; set; }
        public virtual DbSet<formation> formation { get; set; }
        public virtual DbSet<formation_cursus> formation_cursus { get; set; }
        public virtual DbSet<identificateur> identificateur { get; set; }
        public virtual DbSet<salle> salle { get; set; }
        public virtual DbSet<session_cursus> session_cursus { get; set; }
        public virtual DbSet<session_formation> session_formation { get; set; }
        public virtual DbSet<societe> societe { get; set; }
        public virtual DbSet<stagiaire> stagiaire { get; set; }
        public virtual DbSet<stagiaire_session_formation> stagiaire_session_formation { get; set; }
        public virtual DbSet<theme> theme { get; set; }
        public virtual DbSet<theme_formateur> theme_formateur { get; set; }
        public virtual DbSet<ville> ville { get; set; }
    
        public virtual int inscrire_session_formation(Nullable<int> idStagiaire, Nullable<int> idSessionCursus)
        {
            var idStagiaireParameter = idStagiaire.HasValue ?
                new ObjectParameter("idStagiaire", idStagiaire) :
                new ObjectParameter("idStagiaire", typeof(int));
    
            var idSessionCursusParameter = idSessionCursus.HasValue ?
                new ObjectParameter("idSessionCursus", idSessionCursus) :
                new ObjectParameter("idSessionCursus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inscrire_session_formation", idStagiaireParameter, idSessionCursusParameter);
        }
    }
}
