//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gest_formEntities : DbContext
    {
        public gest_formEntities()
            : base("name=gest_formEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bilan_eval_environnement> bilan_eval_environnement { get; set; }
        public virtual DbSet<bilan_eval_formateur> bilan_eval_formateur { get; set; }
        public virtual DbSet<bilan_eval_formation> bilan_eval_formation { get; set; }
        public virtual DbSet<bilan_formation> bilan_formation { get; set; }
        public virtual DbSet<bilan_pointvue_formateur> bilan_pointvue_formateur { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<cursus> cursus { get; set; }
        public virtual DbSet<equipement> equipement { get; set; }
        public virtual DbSet<formateur> formateur { get; set; }
        public virtual DbSet<formateur_session_formation> formateur_session_formation { get; set; }
        public virtual DbSet<formation> formation { get; set; }
        public virtual DbSet<formation_cursus> formation_cursus { get; set; }
        public virtual DbSet<identificateur> identificateur { get; set; }
        public virtual DbSet<personnel> personnel { get; set; }
        public virtual DbSet<salle> salle { get; set; }
        public virtual DbSet<session_cursus> session_cursus { get; set; }
        public virtual DbSet<session_formation> session_formation { get; set; }
        public virtual DbSet<site> site { get; set; }
        public virtual DbSet<societe> societe { get; set; }
        public virtual DbSet<stagiaire> stagiaire { get; set; }
        public virtual DbSet<stagiaire_session_formation> stagiaire_session_formation { get; set; }
        public virtual DbSet<theme> theme { get; set; }
        public virtual DbSet<theme_formateur> theme_formateur { get; set; }
        public virtual DbSet<ville> ville { get; set; }
    }
}
