//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_formation_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class theme_formateur
    {
        public string niveau { get; set; }
        public int id_formateur { get; set; }
        public int id_theme { get; set; }
    
        public virtual formateur formateur { get; set; }
        public virtual theme theme { get; set; }
    }
}
